jokeoverflow/urls.py
from django.conf.urls import url
from jokeoverflow import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'jokeoverflow'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^home/', views.home, name='home'),
    url(r'^about_us/', views.about_us, name='about_us'),
    url(r'^contact_us/', views.contact_us, name='contact_us'),
    url(r'^log_complaint', views.log_complaint, name='log_complaint'),
    url(r'^new_category', views.new_category, name='new_category'),
    url(r'^faq/', views.faq, name='faq'),
    url(r'^latest_news/', views.latest_news, name='latest_news'),
    url(r'^user_profiles/', views.user_profiles, name='user_profiles'),
    url(r'^user_profiles/(?P<username>[\w\-]+)/$', views.user_profiles, name='user_profiles'),
    url(r'^videos/', views.videos, name='videos'),
    url(r'^top_rated_jokes/', views.top_rated_jokes, name='top_rated_jokes'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    url(r'register_profile/', views.register_profile, name='register_profile'),
    url(r'^add/$', views.auto_add_video, name='auto_add_video'),
    url(r'^upvote/$', views.upvote, name='upvote'),
    url(r'^downvote/$', views.downvote, name='downvote'),
    url(r'^video_update/$', views.auto_add_video, name='video_update'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_joke/$', views.add_joke, name='add_joke'),
    url(r'^add_comment/$', views.add_comment, name='add_comment'),
    url(r'edit_profile/', views.edit_profile, name='edit_profile'),
    url(r'^video_remove/$', views.video_remove, name='video_remove'),
    url(r'^joke_remove/$', views.joke_remove, name='joke_remove'),
    url(r'^flag/$', views.flag, name='flag'),
    url(r'^delete/', views.delete_user, name='delete_user'),
    url(r'^suggest_joke/$', views.suggest_joke, name='suggest_joke'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jokeoverflow_wad2_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from jokeoverflow import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.core.urlresolvers import reverse

# redirects user to the index page if successful at logging in
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/jokeoverflow/register_profile/'


app_name = 'jokeoverflow'
urlpatterns = [
                  url(r'^$', views.home, name='home'),
                  url(r'^jokeoverflow/', include('jokeoverflow.urls')),
                  url(r'^admin/', admin.site.urls),
                  url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
                  url(r'^accounts/', include('registration.backends.simple.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jokeoverflow/forms.py
from django import forms
from jokeoverflow.models import UserProfile, Joke, Video, Comment, Category, Complaint, CategoryRequest
from django.contrib.auth.models import User
from django.utils.timezone import now


class UserProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(required=True, widget=forms.SelectDateWidget(years=range(1960, now().year + 1)))
    user_bio = forms.CharField(widget=forms.Textarea, max_length=256, required=False)
    user_picture = forms.ImageField(required=False)
    image_from = forms.URLField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = UserProfile
        exclude = ('user',)

class EditProfileForm(forms.Form):
    user_bio = forms.CharField(widget=forms.Textarea, max_length=256, required=False)
    user_picture = forms.ImageField(required=False)
    image_from = forms.URLField(widget=forms.HiddenInput(), required=False)

    
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class JokeForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text='Give the joke a title.')
    joke_text = forms.CharField(widget=forms.Textarea, max_length=256, help_text='Tell us your joke!')
    date_added = forms.DateTimeField(widget=forms.HiddenInput, required=False)
    upvotes = forms.IntegerField(widget=forms.HiddenInput, initial=0)
    downvotes = forms.IntegerField(widget=forms.HiddenInput, initial=0)
    flagged = forms.BooleanField(widget=forms.HiddenInput, initial=False, required=False)

    class Meta:
        model = Joke
        fields = ('title', 'joke_text')


class VideoForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea, max_length=128, help_text='What\'s the video called?')
    url = forms.URLField(max_length=200, help_text='Please enter the url of the video.')
    upvotes = forms.IntegerField(widget=forms.HiddenInput, initial=0)
    downvotes = forms.IntegerField(widget=forms.HiddenInput, initial=0)
    rating = forms.IntegerField(widget=forms.HiddenInput, initial=0)

    class Meta:
        model = Video
        exclude = ('added_by', 'date_added', 'thumbnail')


class CommentForm(forms.ModelForm):
    comment_text = forms.CharField(max_length=256, help_text='Please enter your comments...', widget=forms.TextInput)

    class Meta:
        model = Comment
        exclude = ('made_by', 'joke', 'date_added')



class CategoryForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the category name.")
    restricted = forms.BooleanField(widget=forms.HiddenInput(), initial=False)
    no_of_jokes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Category
        fields = ('title',)


class ComplaintForm(forms.ModelForm):
    complaint = forms.CharField(widget=forms.Textarea, max_length=256)

    class Meta:
        model = Complaint
        exclude = ('user', 'date_added')

class CategoryRequestForm(forms.ModelForm):
    new_category = forms.CharField(widget=forms.Textarea, max_length=128)

    class Meta:
        model = CategoryRequest
        exclude = ('user', 'date_added')

    

jokeoverflow/views.py
from django.shortcuts import render
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.contrib.auth.decorators import login_required
from jokeoverflow.models import Category, Video, Joke, UserProfile, Comment, Voted
from jokeoverflow.forms import UserProfileForm, EditProfileForm, JokeForm, CategoryRequestForm
from jokeoverflow.models import Category, Video, Joke, UserProfile, Comment, Voted, Complaint
from jokeoverflow.forms import UserProfileForm, JokeForm, CategoryRequestForm
from jokeoverflow.forms import CommentForm, ComplaintForm
from django.shortcuts import redirect
from jokeoverflow.youtube_search import *
from django.template.defaulttags import register
from django.http import HttpResponse
from django.contrib import messages
from jokeoverflow.calculate_age import calculate_age
from django.http import JsonResponse
import json
from django.utils.timezone import now

# Used on several pages, put here to stop duplication.

category_list = Category.objects.order_by('title')
context_dict = {'categories': category_list}

def home(request):
    category_list = Category.objects.order_by('title')
    rec_added_videos = Video.objects.order_by('-date_added')[:5]
    all_jokes = Joke.objects.order_by('-rating')
    rated_clean_jokes = []
    for joke in all_jokes:
        if not joke.category.restricted:
            rated_clean_jokes.append(joke)
    rated_clean_short = []
    rated_clean_short = rated_clean_jokes[:5]

# Home page, sorted jokes in order of rating, removed adult section and then
# indexed to get top 5 rated "clean jokes.
# Similarly below, sorted by date added and removed the adult jokes to get
# most recent clean jokes.

    all_jokes = Joke.objects.order_by('-date_added')
    recent_clean_jokes = []
    for joke in all_jokes:
        if not joke.category.restricted:
            recent_clean_jokes.append(joke)
    recent_clean_short = recent_clean_jokes[:5]

    users = UserProfile.objects.all()
    context_dict = {'categories': category_list, 'recaddedvideos': rec_added_videos, 'topratedjokes': rated_clean_short,
                    'recentjokes': recent_clean_short, 'users': users}
    response = render(request, 'jokeoverflow/home.html', context=context_dict)
    return response


def add_joke(request, category_name_slug):
    category_list = Category.objects.order_by('title')

    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = JokeForm()
    if request.method == 'POST':
        form = JokeForm(request.POST)
        user = request.user

# This is to add a joke to a category. firstly get the correct category
# request the input and fill out form, save new joke

        if form.is_valid():
            if category:
                joke = form.save(commit=False)
                joke.category = category
                joke.added_by = user
                joke.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category, 'categories': category_list}
    return render(request, 'jokeoverflow/add_joke.html', context_dict)

# general about page
def about_us(request):
    return render(request, "jokeoverflow/about_us.html", context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}
    age = 0
    users = UserProfile.objects.all()

    # Check if user is under 18
    if not request.user.is_superuser:
        if request.user.is_authenticated:
            prof = UserProfile.objects.filter(user=request.user)[0]
            age = calculate_age(prof.date_of_birth)

    # Allow superusers to see all categories
    if request.user.is_superuser:
        age = 100

    try:
        category_list = Category.objects.order_by('title')
        category = Category.objects.get(slug=category_name_slug)
        rated_jokes = Joke.objects.filter(category=category).order_by('-rating')[:5]
        recent_jokes = Joke.objects.filter(category=category).order_by('-date_added')[:5]
        all_jokes = Joke.objects.filter(category=category).order_by('-upvotes')
        context_dict = {'categories': category_list, 'category': category, 'topratedjokes': rated_jokes,
                        'recentjokes': recent_jokes, 'alljokes': all_jokes, 'age': age, 'users': users}
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['topratedjokes'] = None
        context_dict['categories'] = None
        context_dict['recentjokes'] = None

    return render(request, 'jokeoverflow/joke_category.html', context=context_dict)

# general contact_us page
def contact_us(request):
    response = render(request, 'jokeoverflow/contact_us.html', context_dict)
    return response

# general FAQ page
def faq(request):
    response = render(request, 'jokeoverflow/faq.html', context_dict)
    return response

# general latest news page
def latest_news(request):
    response = render(request, 'jokeoverflow/latest_news.html', context_dict)
    return response

# get user, delete user.
def delete_user(request):
    context = {}
    u = User.objects.get(username=request.user.username)
    u.delete()      
    
    return render(request, 'jokeoverflow/delete_confirm.html', context)

@login_required
def user_profiles(request):
    userprofile = UserProfile.objects.order_by('user')
    category_list = Category.objects.order_by('title')
    users = UserProfile.objects.all().order_by('user')
    complaints = Complaint.objects.all().order_by('-date_added')
    all_jokes = Joke.objects.all().order_by('id')
    flagged_jokes = Joke.objects.filter(flagged=True).order_by('id');

    # Used to list all entries by a user
    # and to list their details
    form = UserProfileForm(
        {'picture': UserProfile.user_picture, 'bio': UserProfile.user_bio, 'date_of_birth': UserProfile.date_of_birth})

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('profile', request.user.username)

        else:
            print(form.errors)

    return render(request, 'jokeoverflow/user_profiles.html',
                  {'categories': category_list, 'userprofile': userprofile, 'form': form, 'users': users, })

# Allows user to edit profile
def edit_profile(request):
    category_list = Category.objects.order_by('title')
    users = UserProfile.objects.all().order_by('user')
    userprofile = UserProfile.objects.order_by('user')
    form = EditProfileForm(request.POST or None, {'picture': UserProfile.user_picture, 'bio': UserProfile.user_bio })
    # Using editp profile form to change fields
    if request.method == 'POST':
        form = EditProfileForm(request.POST or None, {'picture': UserProfile.user_picture, 'bio': UserProfile.user_bio })
        if form.is_valid():
            obj = UserProfile.objects.get(user=request.user)
            obj.user_picture = form.cleaned_data['user_picture']
            obj.user_bio = form.cleaned_data['user_bio']
            obj.save()
 
            return redirect('/jokeoverflow/user_profiles/')
        else:
            print(form.errors)

    context_dict = {'categories': category_list, 'form': form, 'users':users }

    return render(request, 'jokeoverflow/edit_profile.html', context_dict)


def videos(request):
    # group objects
    category_list = Category.objects.order_by('title')
    rec_added_videos = Video.objects.all().order_by('-date_added')[:5]
    all_videos = Video.objects.all().order_by('title')
    context_dict = {'categories': category_list,
                    'recaddedvideos': rec_added_videos,
                    'allvideos': all_videos,
                    }
    result_list = []
    query = ''
    # use youtube to search 
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = youtube_search(q=query)
    context_dict['previous_query'] = query
    context_dict['result_list'] = result_list

    response = render(request, 'jokeoverflow/videos.html', context_dict)
    return response

@login_required
def log_complaint(request):
    form = ComplaintForm()

    if request.method == 'POST':
        form = ComplaintForm(request.POST)
        if form.is_valid():
            complaint = form.save(commit=False)
            complaint.user = request.user
            complaint.save()
    # again, this logs a complaint on admin page.
    # Calls the form, user completes and is returned by this view
            return redirect('home')
        else:
            print(form.errors)

    category_list = Category.objects.order_by('title')
    context_dict = {'form': form, 'categories': category_list}
    response = render(request, 'jokeoverflow/log_complaint.html', context_dict)
    return response


def top_rated_jokes(request):
    category_list = Category.objects.order_by('title')
    all_jokes = Joke.objects.order_by('-rating')
    rated_clean_jokes = []
    for joke in all_jokes:
        if not joke.category.restricted:
            rated_clean_jokes.append(joke)
    rated_clean_short = []
    rated_clean_short = rated_clean_jokes[:5]
    cat_rated_dict = {}
    for cat in category_list:
        rated_cat_jokes = Joke.objects.filter(category=cat).order_by('-rating')[:5]
        cat_rated_dict[str(cat)] = rated_cat_jokes

# top rated jokes page, sorted jokes in order of rating, removed adult section and then
# indexed to get top 5 rated "clean jokes.
# Similarly below, sorted by date added and removed the adult jokes to get
# most recent clean jokes.

# This adds a comment to a joke
    form = CommentForm(request.POST)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)

templates/jokeoverflow/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head lang="en">
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon4.png' %}">
    <div class="row logo-top" fixed-top>
        <img src="{% static "images/logo2.png" %}" class="img-responsive logo-img" alt="Logo"/>
    </div>
    <!-- Bootstrap core CSS -->
    <!-- <link rel="stylesheet" href="{% static "css/core.css" %}" /> -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static "css/base.css" %}"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href={% static 'lib/css/emoji.css' %} >


    {% block title_block %}
    {% endblock %}
    {% block head_block %}
    {% endblock %}

</head>
<body>


<nav class="navbar navbar-toggleable-md navbar-inverse  bg-inverse">

    <button class="navbar-toggler navbar-toggler-right hidden-lg-up"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
            aria-controls="navbar"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand menu-icon" href="{% url 'jokeoverflow:home' %}">
        <img class="menu-img" border=5px alt="Icon" src="{% static "images/favicon4.PNG" %}">
    </a>
    <!--<img class="navbar-brand menu-icon" href="{% url 'jokeoverflow:home' %}" src="{% static "images/favicon4.png" %}"
    <a class="navbar-brand" href="{% url 'jokeoverflow:home' %}">Joke Overflow</a>
    -->

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'jokeoverflow:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'jokeoverflow:top_rated_jokes' %}">Top Rated Jokes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'jokeoverflow:top_rated_videos' %}">Top Rated Videos</a>
            </li>

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth_logout' %}?next=/jokeoverflow/">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration_register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container-fluid">
    <br>
    <div class="row">
        <div class="col-sm-12 offset-sm-0 col-md-12 offset-md-0 main">
            {% block body_block %}{% endblock %}
        </div>
    </div>
</div>


<footer class="container">

    <ul>
        <a href="{% url 'jokeoverflow:latest_news' %}">Latest News</a> :
        <a class="footer-link" href="{% url 'jokeoverflow:about_us' %}">About Us</a> :


        {% if user.is_authenticated %}
            <a href="{% url 'jokeoverflow:user_profiles' %}">{{ user }}'s Page</a> :
        {% endif %}

        <a href="{% url 'jokeoverflow:contact_us' %}">Contact Us</a> :
        <a href="{% url 'jokeoverflow:faq' %}">FAQ</a> :
	<a href="{% url 'jokeoverflow:new_category' %}">Request New Category</a>
    </ul>

</footer>

<!-- Bootstrap core JavaScript
	================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script
        src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>
<script
        src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
</script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script
        src=
                "http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
</script>
<script
        src="{% static "js/jokeoverflow-jquery.js" %}">
</script>
<script
        src="{% static "js/jquery-3.3.1.min.js " %}">
</script>
<script src="{% static 'lib/js/config.js' %}"></script>
<script src="{% static 'lib/js/util.js' %}"></script>
<script src="{% static 'lib/js/jquery.emojiarea.js' %}"></script>
<script src="{% static 'lib/js/emoji-picker.js' %}"></script>
<script
        src="{% static "js/jokeoverflow-ajax.js" %}">
</script>

</body>
</html>

templates/jokeoverflow/base2.html
<!DOCTYPE html>
{% load staticfiles %}
{% load jokeoverflow_template_tags %}

<html>
<head lang="en">
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon6.png' %}">

    <!--<div class="row logo-top" fixed-top>
        <img src="{% static 'images/logo3.PNG' %}" class="img-responsive logo-img" alt="Logo"/>
    </div>
    -->
    <!-- Bootstrap core CSS -->
    <!-- <link rel="stylesheet" href="{% static "css/core.css" %}" /> -->
    <!-- <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static 'css/core.css' %}" />
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'lib/css/emoji.css' %}" />



    <title>
        JokeOverflow -
        {% block title_block %}
        {% endblock %}
    </title>
    {% block head_block %}
    {% endblock %}

</head>
<body>
<div class="row logo-top" fixed-top>
        <img src="{% static 'images/logo3.PNG' %}" class="img-responsive logo-img" alt="Logo"/>
    </div>

<nav class="navbar navbar-toggleable-md navbar-inverse  bg-inverse">

    <button class="navbar-toggler navbar-toggler-right hidden-lg-up"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
            aria-controls="navbar"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand menu-icon" href="{% url 'jokeoverflow:home' %}">
        <img class="menu-img" border=5px alt="Icon" src="{% static 'images/favicon6.png' %}">
    </a>
    <!--<img class="navbar-brand menu-icon" href="{% url 'jokeoverflow:home' %}" src="{% static "images/favicon4.PNG" %}"
    <a class="navbar-brand" href="{% url 'jokeoverflow:home' %}">Joke Overflow</a>
    -->

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'jokeoverflow:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'jokeoverflow:top_rated_jokes' %}">Top Rated Jokes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'jokeoverflow:videos' %}">Videos</a>
            </li>
	{% if categories %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Categories</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown01">
                    {% if categories %}
                        {% for cat in categories %}
                               <li><a href="{% url 'jokeoverflow:show_category' cat.slug %}">{{ cat.title }}</a></li>
                        {% endfor %}
			<li><a href="{% url 'jokeoverflow:new_category' %}">Req New Category</a></li>
                    {% endif %}
                </ul>
            </li>
	{% endif %}
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth_logout' %}?next=/jokeoverflow/">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration_register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container-fluid">
    <br>
    <div class="row">
        <div class="col-sm-12 offset-sm-0 col-md-12 offset-md-0 main">
            {% block body_block %}{% endblock %}
        </div>
    </div>
</div>


<footer class="container">

    <ul>
        <a href="{% url 'jokeoverflow:latest_news' %}">Latest News</a> :
        <a class="footer-link" href="{% url 'jokeoverflow:about_us' %}">About Us</a> :


        {% if user.is_authenticated %}
           <a href="{% url 'jokeoverflow:user_profiles' user.username %}">Profile</a> :
        {% endif %}

        <a href="{% url 'jokeoverflow:contact_us' %}">Contact Us</a> :
        <a href="{% url 'jokeoverflow:faq' %}">FAQ</a>
    </ul>

</footer>

<!-- Bootstrap core JavaScript
	================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script
        src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>
<script
        src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
</script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script
        src=
                "http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
</script>
<script
        src="{% static "js/jokeoverflow-jquery.js" %}">
</script>
<script
        src="{% static "js/jquery-3.3.1.min.js" %}">
</script>
<script src="{% static 'lib/js/config.js' %}"></script>
<script src="{% static 'lib/js/util.js' %}"></script>
<script src="{% static 'lib/js/jquery.emojiarea.js' %}"></script>
<script src="{% static 'lib/js/emoji-picker.js' %}"></script>
<script
        src="{% static "js/jokeoverflow-ajax.js" %}">
</script>

</body>
</html>

templates/jokeoverflow/home - Copy.html
{% extends 'jokeoverflow/base2.html' %}
{% load staticfiles %}
{% block title_block %}
{% endblock %}
{% block body_block %}
	<h1>This is the HOME page</h1>
	<div>
		<h2> Most Liked Jokes </h2>
		<p>
			{% if topratedjokes %}
				<ul class="list-group">
					{% for joke in topratedjokes %}
						 <li>{{ joke.title }}</li>
					{% endfor %}
				</ul>
			{% else %}
				<strong>There are no jokes present.</strong>
			{% endif %}
		</p>
	</div>
	<div>
		<h2> Most Liked Videos </h2>
		<p>
			{% if topratedvideos %}
				<ul class="list-group">
					{% for video in topratedvideos %}
						<li>{{ video.title }}</li>
					{% endfor %}
				</ul>
			{% else %}
				<strong>There are no videos present.</strong>
			{% endif %}
		</p>
	</div>
	<div>
		<h2> Recently Added Jokes </h2>
		<p>
			{% if recentjokes%}
				<ul class="list-group">
					{% for joke in recentjokes%}
						 <li>{{ joke.title }}</li>
					{% endfor %}
				</ul>
			{% else %}
				<strong>There are no jokes present.</strong>
			{% endif %}
		</p>
	</div>
	{% if categories %}
		<ul class="list-group">
			{% for category in categories %}
				<li class="list-group-item"><a href="{% url 'jokeoverflow:show_category' category.slug %}">
					{{ category.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<strong>There are no categories present.</strong>
	{% endif %}
{% endblock %}